//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply_tab
    {
        public int id { get; set; }
        public int usid { get; set; }
        public int cmpnyid { get; set; }
        public int jobid { get; set; }
        public byte[] resume { get; set; }
        public string date { get; set; }
        public string sts { get; set; }
    }
}
