//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class companytab
    {
        public int cmpny_id { get; set; }
        public string cmpny_name { get; set; }
        public string cmpny_email { get; set; }
        public long cmpny_phone { get; set; }
        public string cmpny_website { get; set; }
    }
}
