//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_details
    {
        public int job_id { get; set; }
        public int company_id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public string job_type { get; set; }
        public string lastdate { get; set; }
        public string status { get; set; }
        public string location { get; set; }
        public int experiance_in_years { get; set; }
        public long salary { get; set; }
        public string skills { get; set; }
    }
}
