//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobsearch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class careerhunt_jobserachEntities1 : DbContext
    {
        public careerhunt_jobserachEntities1()
            : base("name=careerhunt_jobserachEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<companytab> companytabs { get; set; }
        public virtual DbSet<login_tab> login_tab { get; set; }
        public virtual DbSet<district_tab> district_tab { get; set; }
        public virtual DbSet<state_tab> state_tab { get; set; }
        public virtual DbSet<user_reg> user_reg { get; set; }
        public virtual DbSet<job_details> job_details { get; set; }
        public virtual DbSet<apply_tab> apply_tab { get; set; }
    
        public virtual int sp_companyinsert(Nullable<int> cmpnyid, string name, string email, Nullable<long> phone, string web)
        {
            var cmpnyidParameter = cmpnyid.HasValue ?
                new ObjectParameter("cmpnyid", cmpnyid) :
                new ObjectParameter("cmpnyid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            var webParameter = web != null ?
                new ObjectParameter("web", web) :
                new ObjectParameter("web", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyinsert", cmpnyidParameter, nameParameter, emailParameter, phoneParameter, webParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> rid, string username, string password, string logtype, string status)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var logtypeParameter = logtype != null ?
                new ObjectParameter("logtype", logtype) :
                new ObjectParameter("logtype", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", ridParameter, usernameParameter, passwordParameter, logtypeParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_selmaxregid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_selmaxregid");
        }
    
        public virtual ObjectResult<sp_district_Result> sp_district(Nullable<int> sid)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_district_Result>("sp_district", sidParameter);
        }
    
        public virtual ObjectResult<sp_state_Result> sp_state()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_state_Result>("sp_state");
        }
    
        public virtual int sp_userinsert(Nullable<int> rid, string nam, Nullable<int> ag, string addr, string emil, Nullable<long> phn, string pho, string st, Nullable<int> dis, string gen, string dob)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var emilParameter = emil != null ?
                new ObjectParameter("emil", emil) :
                new ObjectParameter("emil", typeof(string));
    
            var phnParameter = phn.HasValue ?
                new ObjectParameter("phn", phn) :
                new ObjectParameter("phn", typeof(long));
    
            var phoParameter = pho != null ?
                new ObjectParameter("pho", pho) :
                new ObjectParameter("pho", typeof(string));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            var disParameter = dis.HasValue ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(int));
    
            var genParameter = gen != null ?
                new ObjectParameter("gen", gen) :
                new ObjectParameter("gen", typeof(string));
    
            var dobParameter = dob != null ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userinsert", ridParameter, namParameter, agParameter, addrParameter, emilParameter, phnParameter, phoParameter, stParameter, disParameter, genParameter, dobParameter);
        }
    
        public virtual int sp_LOGINCOUNTID(string uname, string pass, ObjectParameter status)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LOGINCOUNTID", unameParameter, passParameter, status);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logingetid(string uname, string pass)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logingetid", unameParameter, passParameter);
        }
    
        public virtual ObjectResult<string> sp_Logtype(string uname, string pass)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Logtype", unameParameter, passParameter);
        }
    
        public virtual int sp_jobdetails(Nullable<int> cmpnyid, string jt, string jd, string jty, string lsd, string sts, string lcn, Nullable<int> eiy, Nullable<long> sal, string skl)
        {
            var cmpnyidParameter = cmpnyid.HasValue ?
                new ObjectParameter("cmpnyid", cmpnyid) :
                new ObjectParameter("cmpnyid", typeof(int));
    
            var jtParameter = jt != null ?
                new ObjectParameter("jt", jt) :
                new ObjectParameter("jt", typeof(string));
    
            var jdParameter = jd != null ?
                new ObjectParameter("jd", jd) :
                new ObjectParameter("jd", typeof(string));
    
            var jtyParameter = jty != null ?
                new ObjectParameter("jty", jty) :
                new ObjectParameter("jty", typeof(string));
    
            var lsdParameter = lsd != null ?
                new ObjectParameter("lsd", lsd) :
                new ObjectParameter("lsd", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            var lcnParameter = lcn != null ?
                new ObjectParameter("lcn", lcn) :
                new ObjectParameter("lcn", typeof(string));
    
            var eiyParameter = eiy.HasValue ?
                new ObjectParameter("eiy", eiy) :
                new ObjectParameter("eiy", typeof(int));
    
            var salParameter = sal.HasValue ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(long));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobdetails", cmpnyidParameter, jtParameter, jdParameter, jtyParameter, lsdParameter, stsParameter, lcnParameter, eiyParameter, salParameter, sklParameter);
        }
    
        public virtual ObjectResult<sp_jobs_Result> sp_jobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobs_Result>("sp_jobs");
        }
    
        public virtual int sp_jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearches", qryParameter);
        }
    
        public virtual int sp_apply(Nullable<int> usid, Nullable<int> cmpnyid, Nullable<int> jobid, byte[] cv, string date, string sts)
        {
            var usidParameter = usid.HasValue ?
                new ObjectParameter("usid", usid) :
                new ObjectParameter("usid", typeof(int));
    
            var cmpnyidParameter = cmpnyid.HasValue ?
                new ObjectParameter("cmpnyid", cmpnyid) :
                new ObjectParameter("cmpnyid", typeof(int));
    
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(byte[]));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_apply", usidParameter, cmpnyidParameter, jobidParameter, cvParameter, dateParameter, stsParameter);
        }
    }
}
